package constants

const (
	CondAccountActive                    = "ACCOUNT_ACTIVE"
	CondCustomerOnly                     = "CUSTOMER_ONLY"
	CondCustomerOrAdmin                  = "CUSTOMER_OR_ADMIN"
	CondKYCCompleted                     = "KYC_COMPLETED"
	CondNotArchived                      = "NOT_ARCHIVED"
	CondNotArchivedOrClosed              = "NOT_ARCHIVED_OR_CLOSED"
	CondNotArchivedOrDormant             = "NOT_ARCHIVED_OR_DORMANT"
	CondNotBlacklisted                   = "NOT_BLACKLISTED"
	CondNotBlacklistedOrDeactivated      = "NOT_BLACKLISTED_OR_DEACTIVATED"
	CondNotBlacklistedOrFlagged          = "NOT_BLACKLISTED_OR_FLAGGED"
	CondNotBlacklistedOrRestricted       = "NOT_BLACKLISTED_OR_RESTRICTED"
	CondNotBlocked                       = "NOT_BLOCKED"
	CondNotClosed                        = "NOT_CLOSED"
	CondNotDeactivated                   = "NOT_DEACTIVATED"
	CondNotDeactivatedOrArchived         = "NOT_DEACTIVATED_OR_ARCHIVED"
	CondNotDeactivatedOrDeleted          = "NOT_DEACTIVATED_OR_DELETED"
	CondNotDeactivatedOrDormant          = "NOT_DEACTIVATED_OR_DORMANT"
	CondNotDeleted                       = "NOT_DELETED"
	CondNotDeletedOrClosed               = "NOT_DELETED_OR_CLOSED"
	CondNotDeletedOrDormant              = "NOT_DELETED_OR_DORMANT"
	CondNotDeletedOrUnderMaintenance     = "NOT_DELETED_OR_UNDER_MAINTENANCE"
	CondNotDormant                       = "NOT_DORMANT"
	CondNotDormantOrClosed               = "NOT_DORMANT_OR_CLOSED"
	CondNotFlagged                       = "NOT_FLAGGED"
	CondNotFlaggedOrDeleted              = "NOT_FLAGGED_OR_DELETED"
	CondNotFlaggedOrSuspended            = "NOT_FLAGGED_OR_SUSPENDED"
	CondNotFrozen                        = "NOT_FROZEN"
	CondNotFrozenOrBlacklisted           = "NOT_FROZEN_OR_BLACKLISTED"
	CondNotFrozenOrClosed                = "NOT_FROZEN_OR_CLOSED"
	CondNotFrozenOrDormant               = "NOT_FROZEN_OR_DORMANT"
	CondNotFrozenOrUnderMaintenance      = "NOT_FROZEN_OR_UNDER_MAINTENANCE"
	CondNotRestricted                    = "NOT_RESTRICTED"
	CondNotRestrictedOrArchived          = "NOT_RESTRICTED_OR_ARCHIVED"
	CondNotRestrictedOrDeactivated       = "NOT_RESTRICTED_OR_DEACTIVATED"
	CondNotRestrictedOrSuspended         = "NOT_RESTRICTED_OR_SUSPENDED"
	CondNotSuspended                     = "NOT_SUSPENDED"
	CondNotSuspendedOrClosed             = "NOT_SUSPENDED_OR_CLOSED"
	CondNotUnderMaintenance              = "NOT_UNDER_MAINTENANCE"
	CondNotUnderMaintenanceOrBlacklisted = "NOT_UNDER_MAINTENANCE_OR_BLACKLISTED"
	CondNotUnderMaintenanceOrClosed      = "NOT_UNDER_MAINTENANCE_OR_CLOSED"
	CondNotUnderMaintenanceOrDormant     = "NOT_UNDER_MAINTENANCE_OR_DORMANT"
	CondSufficientBalance                = "SUFFICIENT_BALANCE"
	CondTransferAllowed                  = "TRANSFER_ALLOWED"
)
