package constants

const (
	// Account
	PermAccActivate         = "ACCOUNT_ACTIVATE"
	PermAccArchived         = "ACCOUNT_ARCHIVED"
	PermAccBlacklisted      = "ACCOUNT_BLACKLISTED"
	PermAccBlock            = "ACCOUNT_BLOCK"
	PermAccClose            = "ACCOUNT_CLOSE"
	PermAccCreate           = "ACCOUNT_CREATE"
	PermAccDeactivate       = "ACCOUNT_DEACTIVATE"
	PermAccDelete           = "ACCOUNT_DELETE"
	PermAccDormant          = "ACCOUNT_DORMANT"
	PermAccFlagged          = "ACCOUNT_FLAGGED"
	PermAccFreeze           = "ACCOUNT_FREEZE"
	PermAccOperational      = "ACCOUNT_OPERATIONAL"
	PermAccRead             = "ACCOUNT_READ"
	PermAccReopen           = "ACCOUNT_REOPEN"
	PermAccRestore          = "ACCOUNT_RESTORE"
	PermAccRestricted       = "ACCOUNT_RESTRICTED"
	PermAccSuspended        = "ACCOUNT_SUSPENDED"
	PermAccTransfer         = "ACCOUNT_TRANSFER"
	PermAccUnarchived       = "ACCOUNT_UNARCHIVED"
	PermAccUnblacklisted    = "ACCOUNT_UNBLACKLISTED"
	PermAccUnblock          = "ACCOUNT_UNBLOCK"
	PermAccUnderMaintenance = "ACCOUNT_UNDER_MAINTENANCE"
	PermAccUndormant        = "ACCOUNT_UNDORMANT"
	PermAccUnflagged        = "ACCOUNT_UNFLAGGED"
	PermAccUnfreeze         = "ACCOUNT_UNFREEZE"
	PermAccUnrestricted     = "ACCOUNT_UNRESTRICTED"
	PermAccUnsuspended      = "ACCOUNT_UNSUSPENDED"
	PermAccWrite            = "ACCOUNT_WRITE"

	PermAccTypeCreate = "ACCOUNT_TYPE_CREATE"
	PermAccTypeDelete = "ACCOUNT_TYPE_DELETE"
	PermAccTypeUpdate = "ACCOUNT_TYPE_UPDATE"

	PermAccStatusUpdate    = "ACCOUNT_STATUS_UPDATE"
	PermAccKYCStatusUpdate = "ACCOUNT_KYC_STATUS_UPDATE"

	// Customer
	PermCustManage = "CUSTOMER_MANAGE"
	PermCustRead   = "CUSTOMER_READ"

	// Admin Permission
	PermAdminActivate      = "ADMIN_ACTIVATE"
	PermAdminAssignRole    = "ADMIN_ASSIGN_ROLE"
	PermAdminDeactivate    = "ADMIN_DEACTIVATE"
	PermAdminDelete        = "ADMIN_DELETE"
	PermAdminManage        = "ADMIN_MANAGE"
	PermAdminRead          = "ADMIN_READ"
	PermAdminResetPassword = "ADMIN_RESET_PASSWORD"
	PermAdminRevokeRole    = "ADMIN_REVOKE_ROLE"
	PermAdminSuspend       = "ADMIN_SUSPEND"
	PermAdminUnsuspend     = "ADMIN_UNSUSPEND"
	PermAdminWrite         = "ADMIN_WRITE"

	// Nominee
	PermNomineeApprove = "NOMINEE_APPROVE"
	PermNomineeDelete  = "NOMINEE_DELETE"
	PermNomineeOnHold  = "NOMINEE_ON_HOLD"
	PermNomineeRead    = "NOMINEE_READ"
	PermNomineeReject  = "NOMINEE_REJECT"
	PermNomineeWrite   = "NOMINEE_WRITE"

	// Account Nominee
	PermAccountNomineeApprove = "ACCOUNT_NOMINEE_APPROVE"
	PermAccountNomineeDelete  = "ACCOUNT_NOMINEE_DELETE"
	PermAccountNomineeOnHold  = "ACCOUNT_NOMINEE_ON_HOLD"
	PermAccountNomineeRead    = "ACCOUNT_NOMINEE_READ"
	PermAccountNomineeReject  = "ACCOUNT_NOMINEE_REJECT"
	PermAccountNomineeWrite   = "ACCOUNT_NOMINEE_WRITE"

	// Beneficiary
	PermBeneficiaryApprove = "BENEFICIARY_APPROVE"
	PermBeneficiaryDelete  = "BENEFICIARY_DELETE"
	PermBeneficiaryOnHold  = "BENEFICIARY_ON_HOLD"
	PermBeneficiaryRead    = "BENEFICIARY_READ"
	PermBeneficiaryReject  = "BENEFICIARY_REJECT"
	PermBeneficiaryWrite   = "BENEFICIARY_WRITE"

	// Account Beneficiary
	PermAccountBeneficiaryApprove = "ACCOUNT_BENEFICIARY_APPROVE"
	PermAccountBeneficiaryDelete  = "ACCOUNT_BENEFICIARY_DELETE"
	PermAccountBeneficiaryOnHold  = "ACCOUNT_BENEFICIARY_ON_HOLD"
	PermAccountBeneficiaryRead    = "ACCOUNT_BENEFICIARY_READ"
	PermAccountBeneficiaryReject  = "ACCOUNT_BENEFICIARY_REJECT"
	PermAccountBeneficiaryWrite   = "ACCOUNT_BENEFICIARY_WRITE"

	// Transactions
	PermTransactionChargeback              = "TRANSACTION_CHARGEBACK"
	PermTransactionChargebackAll           = "TRANSACTION_CHARGEBACK_ALL"
	PermTransactionChargebackAllOwn        = "TRANSACTION_CHARGEBACK_ALL_OWN"
	PermTransactionChargebackOthers        = "TRANSACTION_CHARGEBACK_OTHERS"
	PermTransactionChargebackOwn           = "TRANSACTION_CHARGEBACK_OWN"
	PermTransactionDelete                  = "TRANSACTION_DELETE"
	PermTransactionDeleteAll               = "TRANSACTION_DELETE_ALL"
	PermTransactionDeleteAllOthers         = "TRANSACTION_DELETE_ALL_OTHERS"
	PermTransactionDeleteAllOwn            = "TRANSACTION_DELETE_ALL_OWN"
	PermTransactionDeleteOthers            = "TRANSACTION_DELETE_OTHERS"
	PermTransactionDeleteOwn               = "TRANSACTION_DELETE_OWN"
	PermTransactionDispute                 = "TRANSACTION_DISPUTE"
	PermTransactionDisputeAll              = "TRANSACTION_DISPUTE_ALL"
	PermTransactionDisputeAllOthers        = "TRANSACTION_DISPUTE_ALL_OTHERS"
	PermTransactionDisputeAllOwn           = "TRANSACTION_DISPUTE_ALL_OWN"
	PermTransactionDisputeOthers           = "TRANSACTION_DISPUTE_OTHERS"
	PermTransactionDisputeOwn              = "TRANSACTION_DISPUTE_OWN"
	PermTransactionFlag                    = "TRANSACTION_FLAG"
	PermTransactionFlagAll                 = "TRANSACTION_FLAG_ALL"
	PermTransactionFlagAllOthers           = "TRANSACTION_FLAG_ALL_OTHERS"
	PermTransactionFlagAllOwn              = "TRANSACTION_FLAG_ALL_OWN"
	PermTransactionFlagOthers              = "TRANSACTION_FLAG_OTHERS"
	PermTransactionFlagOwn                 = "TRANSACTION_FLAG_OWN"
	PermTransactionRead                    = "TRANSACTION_READ"
	PermTransactionReadAll                 = "TRANSACTION_READ_ALL"
	PermTransactionReadAllOthers           = "TRANSACTION_READ_ALL_OTHERS"
	PermTransactionReadAllOwn              = "TRANSACTION_READ_ALL_OWN"
	PermTransactionReadOthers              = "TRANSACTION_READ_OTHERS"
	PermTransactionReadOwn                 = "TRANSACTION_READ_OWN"
	PermTransactionRefund                  = "TRANSACTION_REFUND"
	PermTransactionResolveDispute          = "TRANSACTION_RESOLVE_DISPUTE"
	PermTransactionResolveDisputeAll       = "TRANSACTION_RESOLVE_DISPUTE_ALL"
	PermTransactionResolveDisputeAllOthers = "TRANSACTION_RESOLVE_DISPUTE_ALL_OTHERS"
	PermTransactionResolveDisputeAllOwn    = "TRANSACTION_RESOLVE_DISPUTE_ALL_OWN"
	PermTransactionResolveDisputeOthers    = "TRANSACTION_RESOLVE_DISPUTE_OTHERS"
	PermTransactionResolveDisputeOwn       = "TRANSACTION_RESOLVE_DISPUTE_OWN"
	PermTransactionReversal                = "TRANSACTION_REVERSAL"
	PermTransactionSettle                  = "TRANSACTION_SETTLE"
	PermTransactionSettleAll               = "TRANSACTION_SETTLE_ALL"
	PermTransactionSettleAllOwn            = "TRANSACTION_SETTLE_ALL_OWN"
	PermTransactionSettleOthers            = "TRANSACTION_SETTLE_OTHERS"
	PermTransactionSettleOwn               = "TRANSACTION_SETTLE_OWN"
	PermTransactionTransfer                = "TRANSACTION_TRANSFER"
	PermTransactionUnflag                  = "TRANSACTION_UNFLAG"
	PermTransactionUnflagAll               = "TRANSACTION_UNFLAG_ALL"
	PermTransactionUnflagAllOthers         = "TRANSACTION_UNFLAG_ALL_OTHERS"
	PermTransactionUnflagAllOwn            = "TRANSACTION_UNFLAG_ALL_OWN"
	PermTransactionUnflagOthers            = "TRANSACTION_UNFLAG_OTHERS"
	PermTransactionUnflagOwn               = "TRANSACTION_UNFLAG_OWN"
	PermTransactionVoid                    = "TRANSACTION_VOID"
	PermTransactionVoidAll                 = "TRANSACTION_VOID_ALL"
	PermTransactionVoidAllOwn              = "TRANSACTION_VOID_ALL_OWN"
	PermTransactionVoidOthers              = "TRANSACTION_VOID_OTHERS"
	PermTransactionVoidOwn                 = "TRANSACTION_VOID_OWN"
	PermTransactionWrite                   = "TRANSACTION_WRITE"
	PermTransactionWriteAll                = "TRANSACTION_WRITE_ALL"
	PermTransactionWriteAllOthers          = "TRANSACTION_WRITE_ALL_OTHERS"
	PermTransactionWriteAllOwn             = "TRANSACTION_WRITE_ALL_OWN"
	PermTransactionWriteOthers             = "TRANSACTION_WRITE_OTHERS"
	PermTransactionWriteOwn                = "TRANSACTION_WRITE_OWN"
)
